### ISSUE TITLE
Update Karma dependency to v0.13 and use new Server interface

### ISSUE THREAD

**Issue by nfriend** [callmehiphop/karma-background#1]
As of Karma v0.13, the server API interface has changed from this: 

``` javascript
var server = require('karma').server;
server.start({port: 9876}, function(exitCode) {
  console.log('Karma has exited with ' + exitCode);
  process.exit(exitCode);
});
```

(taken from http://karma-runner.github.io/0.12/dev/public-api.html)

to this:

``` javascript
var Server = require('karma').Server
var server = new Server({port: 9876}, function(exitCode) {
  console.log('Karma has exited with ' + exitCode)
  process.exit(exitCode)
})
```

(taken from http://karma-runner.github.io/0.13/dev/public-api.html)

This project requires a slight change to how it interacts with the Server object to be compatible with the most recent version of Karma.

**Comment by callmehiphop** [comment]
@nfriend thanks for opening this issue! I haven't used Karma in a little while so I was not aware of this change!

Any interest in opening a PR for this? Otherwise I'm sure I can get to it at some point this week.

**Comment by nfriend** [comment]
Sure, I can submit a pull request.

**Comment by callmehiphop** [comment]
Awesome! Thanks
